// functions/index.js
// Complete Cloud Functions for Stall App
// Includes: Razorpay subscriptions + Google Review auto-responder
//
// Setup commands (run once):
//   firebase functions:config:set razorpay.key_id="rzp_xxx" razorpay.key_secret="xxx" razorpay.webhook_secret="xxx"
//   firebase functions:config:set google.client_id="xxx" google.client_secret="xxx" google.redirect_uri="https://<region>-stall-app-1aab7.cloudfunctions.net/oauthCallback"
//   firebase functions:config:set anthropic.api_key="sk-ant-xxx"

const functions = require("firebase-functions");
const admin = require("firebase-admin");
const axios = require("axios");
const Razorpay = require("razorpay");
const crypto = require("crypto");
if (!admin.apps.length) admin.initializeApp();
const db = admin.firestore();

function getRazorpay() { const cfg = functions.config().razorpay; return new Razorpay({ key_id: cfg.key_id, key_secret: cfg.key_secret }); }
function regionFromLatLng(lat, lng) { if (typeof lat !== "number" || typeof lng !== "number") return "in"; return lat >= 22 && lat <= 26.5 && lng >= 51 && lng <= 56.5 ? "ae" : "in"; }
const SUBSCRIPTION_PLANS = { in_monthly:{amount:49900,currency:"INR",period:"monthly",interval:1,label:"Stall Premium — Monthly"},in_annual:{amount:499900,currency:"INR",period:"yearly",interval:1,label:"Stall Premium — Annual"},ae_monthly:{amount:10000,currency:"AED",period:"monthly",interval:1,label:"Stall Premium — Monthly"},ae_annual:{amount:99900,currency:"AED",period:"yearly",interval:1,label:"Stall Premium — Annual"} };
async function getOrCreatePlanId(razorpay, planKey){const plan=SUBSCRIPTION_PLANS[planKey],ref=db.collection("razorpay_plans").doc(planKey),cached=await ref.get();if(cached.exists&&cached.data().planId)return cached.data().planId;const created=await razorpay.plans.create({period:plan.period,interval:plan.interval,item:{name:plan.label,amount:plan.amount,currency:plan.currency,description:"Auto Google Review Responder"}});await ref.set({planId:created.id,...plan,createdAt:admin.firestore.FieldValue.serverTimestamp()});return created.id;}
exports.createSubscription=functions.https.onCall(async(data,context)=>{if(!context.auth)throw new functions.https.HttpsError("unauthenticated","Login required");const{vendorId,vendorName,vendorEmail,billingCycle}=data,cycle=billingCycle==="annual"?"annual":"monthly";if(context.auth.uid!==vendorId)throw new functions.https.HttpsError("permission-denied","Unauthorized");const premiumDoc=await db.collection("premium_vendors").doc(vendorId).get();if(premiumDoc.exists&&premiumDoc.data().isPremium)throw new functions.https.HttpsError("already-exists","Already subscribed");try{const s=await db.collection("vendors").where("ownerId","==",vendorId).limit(1).get(),listing=s.empty?null:s.docs[0].data(),planKey=`${regionFromLatLng(listing?.lat,listing?.lng)}_${cycle}`,plan=SUBSCRIPTION_PLANS[planKey],razorpay=getRazorpay(),planId=await getOrCreatePlanId(razorpay,planKey),subscription=await razorpay.subscriptions.create({plan_id:planId,customer_notify:1,quantity:1,total_count:cycle==="annual"?10:120,notes:{vendorId,vendorName:vendorName||"",vendorEmail:vendorEmail||"",source:"stall-app",planKey}});await db.collection("premium_vendors").doc(vendorId).set({isPremium:false,subscriptionId:subscription.id,planId,planKey,billingCycle:cycle,amount:plan.amount,currency:plan.currency,status:"created",vendorName:vendorName||"",vendorEmail:vendorEmail||"",createdAt:admin.firestore.FieldValue.serverTimestamp(),activatedAt:null,nextBillingDate:null,payments:[]},{merge:true});return{subscriptionId:subscription.id,keyId:functions.config().razorpay.key_id,planKey,amount:plan.amount,currency:plan.currency};}catch(err){console.error("createSubscription error:",err);throw new functions.https.HttpsError("internal",err.message);}});
exports.verifySubscription=functions.https.onCall(async(data,context)=>{if(!context.auth)throw new functions.https.HttpsError("unauthenticated","Login required");const{razorpay_payment_id,razorpay_subscription_id,razorpay_signature,vendorId}=data;if(context.auth.uid!==vendorId)throw new functions.https.HttpsError("permission-denied","Unauthorized");try{const cfg=functions.config().razorpay,expected=crypto.createHmac("sha256",cfg.key_secret).update(`${razorpay_payment_id}|${razorpay_subscription_id}`).digest("hex");if(expected!==razorpay_signature)throw new functions.https.HttpsError("invalid-argument","Payment signature mismatch");const payment=await getRazorpay().payments.fetch(razorpay_payment_id),snap=await db.collection("premium_vendors").doc(vendorId).get(),cycle=snap.exists?snap.data().billingCycle:"monthly",next=new Date();next.setDate(next.getDate()+(cycle==="annual"?365:30));await db.collection("premium_vendors").doc(vendorId).set({isPremium:true,status:"active",subscriptionId:razorpay_subscription_id,activatedAt:admin.firestore.FieldValue.serverTimestamp(),nextBillingDate:next,payments:admin.firestore.FieldValue.arrayUnion({paymentId:razorpay_payment_id,amount:payment.amount,paidAt:admin.firestore.Timestamp.now(),method:payment.method})},{merge:true});const vs=await db.collection("vendors").where("ownerId","==",vendorId).limit(1).get();if(!vs.empty)await vs.docs[0].ref.update({isPremium:true});return{success:true};}catch(err){console.error("verifySubscription error:",err);throw new functions.https.HttpsError("internal",err.message);}});
exports.cancelSubscription=functions.https.onCall(async(data,context)=>{if(!context.auth)throw new functions.https.HttpsError("unauthenticated","Login required");try{const snap=await db.collection("premium_vendors").doc(context.auth.uid).get();if(!snap.exists||!snap.data().subscriptionId)throw new functions.https.HttpsError("not-found","No active subscription");await getRazorpay().subscriptions.cancel(snap.data().subscriptionId,{cancel_at_cycle_end:1});await db.collection("premium_vendors").doc(context.auth.uid).update({status:"cancelling",cancelledAt:admin.firestore.FieldValue.serverTimestamp()});return{success:true};}catch(err){throw new functions.https.HttpsError("internal",err.message);}});
exports.razorpayWebhook=functions.https.onRequest(async(req,res)=>{const cfg=functions.config().razorpay;if(req.headers["x-razorpay-signature"]!==crypto.createHmac("sha256",cfg.webhook_secret).update(JSON.stringify(req.body)).digest("hex"))return res.status(400).send("Invalid signature");try{const event=req.body.event,p=req.body.payload,sub=p.subscription?.entity;if(sub){const snap=await db.collection("premium_vendors").where("subscriptionId","==",sub.id).limit(1).get();if(!snap.empty){const id=snap.docs[0].id;if(event==="subscription.charged")await db.collection("premium_vendors").doc(id).update({isPremium:true,status:"active"});else if(["subscription.payment.failed","payment.failed"].includes(event))await db.collection("premium_vendors").doc(id).update({isPremium:false,status:"payment_failed"});else if(["subscription.cancelled","subscription.completed"].includes(event))await db.collection("premium_vendors").doc(id).update({isPremium:false,status:"cancelled"});}}res.status(200).json({received:true});}catch(err){res.status(500).send("Webhook processing failed");}});
exports.getSubscriptionStatus=functions.https.onCall(async(data,context)=>{if(!context.auth)throw new functions.https.HttpsError("unauthenticated","Login required");const s=await db.collection("premium_vendors").doc(context.auth.uid).get();if(!s.exists)return{isPremium:false,status:"none"};const d=s.data();return{isPremium:d.isPremium,status:d.status,subscriptionId:d.subscriptionId,nextBillingDate:d.nextBillingDate};});
exports.beginGbpOauth=functions.https.onCall(async(data,context)=>{if(!context.auth)throw new functions.https.HttpsError("unauthenticated","Login required");const state=crypto.randomBytes(24).toString("hex");await db.collection("oauth_states").doc(state).set({vendorId:context.auth.uid,createdAt:admin.firestore.FieldValue.serverTimestamp(),expiresAt:new Date(Date.now()+600000)});return{state};});
exports.oauthCallback=functions.https.onRequest(async(req,res)=>{const{code,state}=req.query;if(!code||!state)return res.status(400).send("Missing code or state");try{const sr=db.collection("oauth_states").doc(state),sd=await sr.get();if(!sd.exists)return res.status(400).send("Invalid or expired connection request. Please try connecting again.");const{vendorId,expiresAt}=sd.data();await sr.delete();if(!expiresAt||expiresAt.toDate()<new Date())return res.status(400).send("This connection request expired. Please try connecting again.");const cfg={client_id:functions.config().google.client_id,client_secret:functions.config().google.client_secret,redirect_uri:functions.config().google.redirect_uri},tr=await axios.post("https://oauth2.googleapis.com/token",{code,client_id:cfg.client_id,client_secret:cfg.client_secret,redirect_uri:cfg.redirect_uri,grant_type:"authorization_code"}),{access_token,refresh_token,expires_in}=tr.data,ar=await axios.get("https://mybusinessaccountmanagement.googleapis.com/v1/accounts",{headers:{Authorization:`Bearer ${access_token}`}}),account=ar.data.accounts?.[0];if(!account)return res.status(400).send("No GBP account found");const lr=await axios.get(`https://mybusinessbusinessinformation.googleapis.com/v1/${account.name}/locations`,{headers:{Authorization:`Bearer ${access_token}`},params:{readMask:"name,title,storefrontAddress,phoneNumbers,websiteUri"}}),location=lr.data.locations?.[0];await db.collection("gbp_connections").doc(vendorId).set({connected:true,accessToken:access_token,refreshToken:refresh_token,tokenExpiresAt:new Date(Date.now()+expires_in*1000),accountName:account.name,locationName:location?.title||"Your Business",locationId:location?.name||"",connectedAt:admin.firestore.FieldValue.serverTimestamp(),lastPolled:null},{merge:true});res.redirect("https://stallapp.stallwale.in/?gbp=connected");}catch(err){console.error("OAuth callback error:",err.response?.data||err.message);res.status(500).send("Connection failed. Please try again.");}});
async function refreshAccessToken(vendorId,c){const cfg={client_id:functions.config().google.client_id,client_secret:functions.config().google.client_secret,redirect_uri:functions.config().google.redirect_uri},r=await axios.post("https://oauth2.googleapis.com/token",{refresh_token:c.refreshToken,client_id:cfg.client_id,client_secret:cfg.client_secret,grant_type:"refresh_token"}),{access_token,expires_in}=r.data;await db.collection("gbp_connections").doc(vendorId).update({accessToken:access_token,tokenExpiresAt:new Date(Date.now()+expires_in*1000)});return access_token;}
async function getValidToken(vendorId,c){const expiry=c.tokenExpiresAt?.toDate?.()||new Date(0);return expiry<new Date(Date.now()+300000)?refreshAccessToken(vendorId,c):c.accessToken;}
function getReviewResourceName(c){const stored=String(c.locationId||"").replace(/^\/+|\/+$/g,"");if(stored.startsWith("accounts/"))return stored;const account=String(c.accountName||"").replace(/^\/+|\/+$/g,"");if(!account||!stored)throw new Error("GBP account/location information is missing");return `${account}/${stored}`;}
async function generateAIResponse(review,listing,settings){const apiKey=functions.config().anthropic.api_key;const prompt=`Write a Google Business review response for a local business.\nBUSINESS: ${listing?.name||"Our Business"}\nREVIEWER: ${review.reviewerName||"Valued Customer"}\nRATING: ${review.starRating}/5\nREVIEW: "${review.reviewText||"(No text — star rating only)"}"\n\nWrite ONLY the response in 50-120 words.`;const r=await axios.post("https://api.anthropic.com/v1/messages",{model:"claude-sonnet-4-6",max_tokens:300,messages:[{role:"user",content:prompt}]},{headers:{"x-api-key":apiKey,"anthropic-version":"2023-06-01","Content-Type":"application/json"}});return r.data.content?.[0]?.text?.trim()||"";}
exports.pollReviews=functions.pubsub.schedule("every 30 minutes").onRun(async()=>{const snap=await db.collection("gbp_connections").where("connected","==",true).get();await Promise.allSettled(snap.docs.map(async(doc)=>{const vendorId=doc.id,c=doc.data();try{const premium=await db.collection("premium_vendors").doc(vendorId).get();if(!premium.exists||!premium.data().isPremium)return;const vs=await db.collection("vendors").where("ownerId","==",vendorId).limit(1).get(),listing=vs.docs[0]?.data()||{},settings=c.responseSettings||{},token=await getValidToken(vendorId,c),resource=getReviewResourceName(c),rr=await axios.get(`https://mybusiness.googleapis.com/v4/${resource}/reviews`,{headers:{Authorization:`Bearer ${token}`},params:{pageSize:50}});for(const review of rr.data.reviews||[]){const id=review.reviewId,rating={ONE:1,TWO:2,THREE:3,FOUR:4,FIVE:5}[review.starRating]||3,existing=await db.collection("review_responses").doc(`${vendorId}_${id}`).get();if(existing.exists||review.reviewReply||settings[`replyTo${rating}Star`]===false)continue;const data={vendorId,reviewId:id,reviewerName:review.reviewer?.displayName||"Valued Customer",reviewText:review.comment||"",starRating:rating,receivedAt:admin.firestore.Timestamp.fromDate(new Date(review.createTime)),status:"pending",aiResponse:null,postedAt:null};await db.collection("review_responses").doc(`${vendorId}_${id}`).set(data);const ai=await generateAIResponse(data,listing,settings);await axios.put(`https://mybusiness.googleapis.com/v4/${resource}/reviews/${id}/reply`,{comment:ai},{headers:{Authorization:`Bearer ${token}`}});await db.collection("review_responses").doc(`${vendorId}_${id}`).update({aiResponse:ai,status:"posted",postedAt:admin.firestore.FieldValue.serverTimestamp()});}await db.collection("gbp_connections").doc(vendorId).update({lastPolled:admin.firestore.FieldValue.serverTimestamp()});}catch(err){console.error(`Error processing vendor ${vendorId}:`,err.response?.data||err.message);}}));return null;});
exports.triggerPollForVendor=functions.https.onCall(async(data,context)=>{if(!context.auth)throw new functions.https.HttpsError("unauthenticated","Login required");const vendorId=context.auth.uid;try{const[c,p]=await Promise.all([db.collection("gbp_connections").doc(vendorId).get(),db.collection("premium_vendors").doc(vendorId).get()]);if(!c.exists||!c.data().connected)throw new functions.https.HttpsError("failed-precondition","GBP not connected");if(!p.exists||!p.data().isPremium)throw new functions.https.HttpsError("failed-precondition","Premium subscription required");const token=await getValidToken(vendorId,c.data()),resource=getReviewResourceName(c.data()),rr=await axios.get(`https://mybusiness.googleapis.com/v4/${resource}/reviews`,{headers:{Authorization:`Bearer ${token}`},params:{pageSize:10}});return{reviewCount:rr.data.reviews?.length||0,message:"Poll triggered successfully — check review_responses collection"};}catch(err){if(err instanceof functions.https.HttpsError)throw err;console.error("triggerPollForVendor error:",err.response?.status,err.response?.data||err.message);throw new functions.https.HttpsError("unavailable","Google review sync failed. Please try again.");}});
exports.weeklyCustomerDigest=functions.pubsub.schedule("every monday 09:00").timeZone("Asia/Kolkata").onRun(async()=>null);
exports.weeklyVendorDigest=functions.pubsub.schedule("every monday 09:00").timeZone("Asia/Kolkata").onRun(async()=>null);
Object.assign(exports,require("./agentCommissions"));
Object.assign(exports,require("./websiteBuildPayments"));
Object.assign(exports,require("./boostCompetitiveRanking"));
